### ISSUE TITLE
CH ORF Consent (Gabriel Hess, BFH I4MI)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#151]
ch.fhir.ig.ch-orf#2.0.0-ballot /StructureDefinition-ch-orf-consent.html

ORF Consent hat eine policyRule mit dem fixed Coding 385432009 = "not applicable"? policyRule hat 0..1 Kardinalität, warum gibt man hier einen nichts sagenden Wert vor?

Gabriel Hess, BFH I4MI

**Comment by oliveregger** [comment]
<img width="732" alt="image" src="https://github.com/hl7ch/ch-orf/assets/2414516/821ecfc2-70d2-4fdc-baee-f245e378a958">

**Comment by oliveregger** [comment]
this looks strange 0..* as well as 1..*

**Comment by JBleuer** [comment]
Descripiton of constraints in Consent resource: A healthcare consumer's choices to permit or deny recipients or roles to perform actions for specific purposes and periods of time.
The  Value Set http://hl7.org/fhir/ValueSet/consent-policy is extensible, however it shows what is meant. Nothing apllies to our use case. That is the reason for fixed Coding 385432009 = "not applicable"; we need it because of the rule.
