### ISSUE TITLE
Questionnaire ORF: Composition.title / .type / .category (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-orf#31]
ch.fhir.ig.ch-orf#0.10.0 /questionnaire.html

Add description for the handling of the three fields order.title, order.type and order.category. According to this [issue from CH RAD-Order](https://github.com/hl7ch/ch-rad-order/issues/5).

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
title
- aus dem Questionnaire entfernen
- Profil: fixedValue in den abgeleiteten IG's
type
- auf Ebene Austauschformat definieren -> Profil
- nicht im Questionnaire abbilden
category
- etoc ist nicht order
- auf Ebene Austauschformat definieren -> Profil
- nicht im Questionnaire abbilden

**Comment by JBleuer** [comment]
See also Issue from RAD-Order:  Questionnaire: readonly fields (Michaela Ziegler, ahdis ag) #5 
The values for the readonly fields order.title, order.type, order.category must be defined fix for the CH RAD-Order Questionnaire. It is to be discussed where this should be done (Questionnaire, QuestionnaireResponse).
This must then be described in the IG CH ORF because it affects all derived exchange formats.

See https://github.com/hl7ch/ch-rad-order/issues/5#issue-980297183

**Comment by oliveregger** [comment]
mapping io

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
